import type { Metadata } from 'next';
import { PageShell } from '@/components/site/PageShell';
import { OfficialDisclaimer } from '@/components/site/OfficialDisclaimer';
import { Card } from '@/components/ui/Card';
import { ButtonLink } from '@/components/ui/ButtonLink';

export const metadata: Metadata = { title: 'FachkundePilot — Deutsche Fachkundeprüfungen gezielt bestehen', description: 'Lernplattform für deutsche Fachkundeprüfungen mit Lernkarten, Fragen, Simulationen und Lernpfaden.' };
const certs=['Taxi & Mietwagen','§34a Bewachung','Güterkraftverkehr','Versicherung §34d','Finanzanlagen §34f','Immobiliardarlehen'];
export default function HomePage(){return <PageShell><main className='mx-auto max-w-6xl space-y-12 px-5 py-10 md:py-14'>
<section className='grid gap-6 rounded-3xl border border-sky-400/15 bg-[#071a2e] p-6 md:grid-cols-2 md:p-8'><div><h1 className='text-4xl font-bold text-white md:text-5xl'>Deutsche Fachkundeprüfungen gezielt bestehen.</h1><p className='mt-4 text-slate-300'>Lerne deutsche Prüfungsbegriffe, verstehe sie in deiner Sprache und trainiere mit Lernkarten, Simulationen und klaren Lernpfaden.</p><div className='mt-6 flex flex-wrap gap-3'><ButtonLink href='/zertifikate'>Zertifikat auswählen</ButtonLink><ButtonLink href='/dashboard' variant='secondary'>Demo ansehen</ButtonLink></div></div><Card><p className='text-slate-300'>Dashboard-Vorschau</p><div className='mt-4 space-y-3'>{['Lernpfad aktiv','Wiederholung heute','Simulation bereit'].map(i=><div key={i} className='rounded-lg border border-slate-700 bg-[#071a2e] p-3 text-sm'>{i}</div>)}</div></Card></section>
<section className='grid gap-3 sm:grid-cols-2 lg:grid-cols-5'>{['Multiple German exams','Mehrsprachige Erklärungen','Lernkarten & Wiederholung','Prüfungssimulation','Fortschrittsanalyse'].map(i=><Card key={i} className='text-sm text-slate-200'>{i}</Card>)}</section>
<section id='problem' className='grid gap-4 md:grid-cols-2'><Card><h2 className='text-2xl font-semibold'>Das Problem</h2><ul className='mt-3 list-disc space-y-1 pl-5 text-slate-300'><li>PDFs sind oft chaotisch.</li><li>Prüfungssprache ist anspruchsvoll.</li><li>Realistische Simulation fehlt.</li><li>Rechnen ist häufig der größte Blocker.</li></ul></Card><Card><h2 className='text-2xl font-semibold'>Die Methode</h2><ul className='mt-3 list-disc space-y-1 pl-5 text-slate-300'><li>Deutsche Originalbegriffe</li><li>Einfache Erklärungen in AR/EN/TR</li><li>Flashcards, Fragen, Simulation</li><li>Fortschrittsanalyse und Wiederholung</li></ul></Card></section>
<section><h2 className='text-2xl font-semibold'>Zertifikate</h2><div className='mt-4 grid gap-3 md:grid-cols-3'>{certs.map(c=><Card key={c}><p className='font-semibold'>{c}</p><ButtonLink href='/zertifikate' variant='ghost'>Mehr erfahren</ButtonLink></Card>)}</div></section>
<section className='grid gap-4 md:grid-cols-2'><Card><h3 className='text-xl font-semibold'>Learning App Vorschau</h3><p className='mt-2 text-slate-300'>Dashboard, Lernpfad, Lernkarten, Fragen und lokale Fortschrittsdaten sind vorbereitet.</p></Card><Card><h3 className='text-xl font-semibold'>Preise</h3><p className='mt-2 text-slate-300'>Kostenlos · Einzelzertifikat · Alle Zertifikate · Akademie</p><ButtonLink href='/preise' variant='secondary'>Zu den Preisen</ButtonLink></Card></section>
<section className='rounded-2xl border border-slate-700 bg-[#0b1d33] p-6 text-center'><h2 className='text-2xl font-semibold'>Starte mit einem klaren Lernpfad.</h2><div className='mt-5 flex flex-wrap justify-center gap-3'><ButtonLink href='/zertifikate'>Zertifikat auswählen</ButtonLink><ButtonLink href='/kontakt' variant='secondary'>Kontakt</ButtonLink></div><div className='mt-4'><OfficialDisclaimer /></div></section>
</main></PageShell>}
